### Registrar um novo usuário
POST http://localhost:3001/api/users/register
Content-Type: application/json

{
  "name": "Teste User",
  "email": "teste@email.com",
  "password": "password123"
}

###

### Fazer login para obter o token
# @name loginRequest
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
  "email": "teste@email.com",
  "password": "password123"
}

###
@token = {{loginRequest.response.body.token}}